server:
  port: 4000

spring:
  application:
    name: API GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: JOB-SERVICE
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/test/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
