server:
  port: 4004
spring:
  application:
    name: JOB
#  datasource:
#    username: root
#    password: database
#    url: jdbc:mysql://3.12.123.70:3306/BC33GreenCommute
#    driverClassName: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost